//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsManagementSystem.StudentsManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateStudentCommand", Namespace="http://schemas.datacontract.org/2004/07/StudentsManagementService.Command.Student" +
        "Commands")]
    [System.SerializableAttribute()]
    public partial class CreateStudentCommand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GpiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gpi {
            get {
                return this.GpiField;
            }
            set {
                if ((this.GpiField.Equals(value) != true)) {
                    this.GpiField = value;
                    this.RaisePropertyChanged("Gpi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentListQuery", Namespace="http://schemas.datacontract.org/2004/07/StudentsManagementService.Queries.Student" +
        "Queries")]
    [System.SerializableAttribute()]
    public partial class StudentListQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WCF.Domain.StudentsManagement")]
    [System.SerializableAttribute()]
    public partial class Student : StudentsManagementSystem.StudentsManagementService.AggregateRoot {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GpiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gpi {
            get {
                return this.GpiField;
            }
            set {
                if ((this.GpiField.Equals(value) != true)) {
                    this.GpiField = value;
                    this.RaisePropertyChanged("Gpi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/WCF.Shared")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StudentsManagementSystem.StudentsManagementService.AggregateRoot))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StudentsManagementSystem.StudentsManagementService.Student))]
    public partial class Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AggregateRoot", Namespace="http://schemas.datacontract.org/2004/07/WCF.Shared")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StudentsManagementSystem.StudentsManagementService.Student))]
    public partial class AggregateRoot : StudentsManagementSystem.StudentsManagementService.Entity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateStudentCommand", Namespace="http://schemas.datacontract.org/2004/07/StudentsManagementService.Command.Student" +
        "Commands")]
    [System.SerializableAttribute()]
    public partial class UpdateStudentCommand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteStudentCommand", Namespace="http://schemas.datacontract.org/2004/07/StudentsManagementService.Command.Student" +
        "Commands")]
    [System.SerializableAttribute()]
    public partial class DeleteStudentCommand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentsManagementService.IExecutorService")]
    public interface IExecutorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecutorService/CreateStudent", ReplyAction="http://tempuri.org/IExecutorService/CreateStudentResponse")]
        bool CreateStudent(StudentsManagementSystem.StudentsManagementService.CreateStudentCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecutorService/CreateStudent", ReplyAction="http://tempuri.org/IExecutorService/CreateStudentResponse")]
        System.Threading.Tasks.Task<bool> CreateStudentAsync(StudentsManagementSystem.StudentsManagementService.CreateStudentCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecutorService/ReadStudent", ReplyAction="http://tempuri.org/IExecutorService/ReadStudentResponse")]
        StudentsManagementSystem.StudentsManagementService.Student[] ReadStudent(StudentsManagementSystem.StudentsManagementService.StudentListQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecutorService/ReadStudent", ReplyAction="http://tempuri.org/IExecutorService/ReadStudentResponse")]
        System.Threading.Tasks.Task<StudentsManagementSystem.StudentsManagementService.Student[]> ReadStudentAsync(StudentsManagementSystem.StudentsManagementService.StudentListQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecutorService/UpdateStudent", ReplyAction="http://tempuri.org/IExecutorService/UpdateStudentResponse")]
        bool UpdateStudent(StudentsManagementSystem.StudentsManagementService.UpdateStudentCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecutorService/UpdateStudent", ReplyAction="http://tempuri.org/IExecutorService/UpdateStudentResponse")]
        System.Threading.Tasks.Task<bool> UpdateStudentAsync(StudentsManagementSystem.StudentsManagementService.UpdateStudentCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecutorService/DeleteStudent", ReplyAction="http://tempuri.org/IExecutorService/DeleteStudentResponse")]
        bool DeleteStudent(StudentsManagementSystem.StudentsManagementService.DeleteStudentCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecutorService/DeleteStudent", ReplyAction="http://tempuri.org/IExecutorService/DeleteStudentResponse")]
        System.Threading.Tasks.Task<bool> DeleteStudentAsync(StudentsManagementSystem.StudentsManagementService.DeleteStudentCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExecutorServiceChannel : StudentsManagementSystem.StudentsManagementService.IExecutorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecutorServiceClient : System.ServiceModel.ClientBase<StudentsManagementSystem.StudentsManagementService.IExecutorService>, StudentsManagementSystem.StudentsManagementService.IExecutorService {
        
        public ExecutorServiceClient() {
        }
        
        public ExecutorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecutorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateStudent(StudentsManagementSystem.StudentsManagementService.CreateStudentCommand command) {
            return base.Channel.CreateStudent(command);
        }
        
        public System.Threading.Tasks.Task<bool> CreateStudentAsync(StudentsManagementSystem.StudentsManagementService.CreateStudentCommand command) {
            return base.Channel.CreateStudentAsync(command);
        }
        
        public StudentsManagementSystem.StudentsManagementService.Student[] ReadStudent(StudentsManagementSystem.StudentsManagementService.StudentListQuery query) {
            return base.Channel.ReadStudent(query);
        }
        
        public System.Threading.Tasks.Task<StudentsManagementSystem.StudentsManagementService.Student[]> ReadStudentAsync(StudentsManagementSystem.StudentsManagementService.StudentListQuery query) {
            return base.Channel.ReadStudentAsync(query);
        }
        
        public bool UpdateStudent(StudentsManagementSystem.StudentsManagementService.UpdateStudentCommand command) {
            return base.Channel.UpdateStudent(command);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStudentAsync(StudentsManagementSystem.StudentsManagementService.UpdateStudentCommand command) {
            return base.Channel.UpdateStudentAsync(command);
        }
        
        public bool DeleteStudent(StudentsManagementSystem.StudentsManagementService.DeleteStudentCommand command) {
            return base.Channel.DeleteStudent(command);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStudentAsync(StudentsManagementSystem.StudentsManagementService.DeleteStudentCommand command) {
            return base.Channel.DeleteStudentAsync(command);
        }
    }
}
